//go:build go1.22

// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for BuildMode.
const (
	BuildModePreRenewal BuildMode = "pre-renewal"
	BuildModeRenewal    BuildMode = "renewal"
)

// Valid indicates whether the value is a known member of the BuildMode enum.
func (e BuildMode) Valid() bool {
	switch e {
	case BuildModePreRenewal:
		return true
	case BuildModeRenewal:
		return true
	default:
		return false
	}
}

// Defines values for BuildTier.
const (
	Budget    BuildTier = "budget"
	Endgame   BuildTier = "endgame"
	Realistic BuildTier = "realistic"
)

// Valid indicates whether the value is a known member of the BuildTier enum.
func (e BuildTier) Valid() bool {
	switch e {
	case Budget:
		return true
	case Endgame:
		return true
	case Realistic:
		return true
	default:
		return false
	}
}

// Defines values for GateResultSeverity.
const (
	Fail     GateResultSeverity = "fail"
	FailHard GateResultSeverity = "fail_hard"
	Pass     GateResultSeverity = "pass"
	Warn     GateResultSeverity = "warn"
)

// Valid indicates whether the value is a known member of the GateResultSeverity enum.
func (e GateResultSeverity) Valid() bool {
	switch e {
	case Fail:
		return true
	case FailHard:
		return true
	case Pass:
		return true
	case Warn:
		return true
	default:
		return false
	}
}

// Defines values for GenerateRequestMode.
const (
	GenerateRequestModePreRenewal GenerateRequestMode = "pre-renewal"
	GenerateRequestModeRenewal    GenerateRequestMode = "renewal"
)

// Valid indicates whether the value is a known member of the GenerateRequestMode enum.
func (e GenerateRequestMode) Valid() bool {
	switch e {
	case GenerateRequestModePreRenewal:
		return true
	case GenerateRequestModeRenewal:
		return true
	default:
		return false
	}
}

// Defines values for GenerateRequestPlaystyle.
const (
	BalancedDual       GenerateRequestPlaystyle = "balanced_dual"
	BalancedGeneralist GenerateRequestPlaystyle = "balanced_generalist"
	Pvm                GenerateRequestPlaystyle = "pvm"
	Pvp                GenerateRequestPlaystyle = "pvp"
)

// Valid indicates whether the value is a known member of the GenerateRequestPlaystyle enum.
func (e GenerateRequestPlaystyle) Valid() bool {
	switch e {
	case BalancedDual:
		return true
	case BalancedGeneralist:
		return true
	case Pvm:
		return true
	case Pvp:
		return true
	default:
		return false
	}
}

// Defines values for GenerationStatusStatus.
const (
	Completed GenerationStatusStatus = "completed"
	Failed    GenerationStatusStatus = "failed"
	Queued    GenerationStatusStatus = "queued"
	Running   GenerationStatusStatus = "running"
)

// Valid indicates whether the value is a known member of the GenerationStatusStatus enum.
func (e GenerationStatusStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case Failed:
		return true
	case Queued:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// Defines values for SlotKey.
const (
	Accessory1 SlotKey = "accessory1"
	Accessory2 SlotKey = "accessory2"
	Armor      SlotKey = "armor"
	Footgear   SlotKey = "footgear"
	Garment    SlotKey = "garment"
	HeadBot    SlotKey = "headBot"
	HeadMid    SlotKey = "headMid"
	HeadTop    SlotKey = "headTop"
	Shield     SlotKey = "shield"
	Weapon     SlotKey = "weapon"
)

// Valid indicates whether the value is a known member of the SlotKey enum.
func (e SlotKey) Valid() bool {
	switch e {
	case Accessory1:
		return true
	case Accessory2:
		return true
	case Armor:
		return true
	case Footgear:
		return true
	case Garment:
		return true
	case HeadBot:
		return true
	case HeadMid:
		return true
	case HeadTop:
		return true
	case Shield:
		return true
	case Weapon:
		return true
	default:
		return false
	}
}

// BasePlus defines model for BasePlus.
type BasePlus struct {
	Base int `json:"base"`
	Plus int `json:"plus"`
}

// Build defines model for Build.
type Build struct {
	// Class shim-contract class name ("novice", "taekwon_kid", ...)
	Class *string `json:"class,omitempty"`

	// Equipment keyed by SlotKey enum (weapon, headTop, ...)
	Equipment *EquipmentMap `json:"equipment,omitempty"`
	Level     Level         `json:"level"`

	// Mode only "pre-renewal" is currently supported
	Mode   *BuildMode `json:"mode,omitempty"`
	Server *string    `json:"server,omitempty"`
	Stats  Stats      `json:"stats"`
	Tier   *BuildTier `json:"tier,omitempty"`
}

// BuildMode only "pre-renewal" is currently supported
type BuildMode string

// BuildTier defines model for Build.Tier.
type BuildTier string

// BuildSummary defines model for BuildSummary.
type BuildSummary struct {
	Class       string      `json:"class"`
	CreatedAt   time.Time   `json:"created_at"`
	Description *string     `json:"description,omitempty"`
	GateSummary GateSummary `json:"gate_summary"`
	Id          string      `json:"id"`
	Playstyle   string      `json:"playstyle"`
	Server      string      `json:"server"`
}

// CombatCrit defines model for CombatCrit.
type CombatCrit struct {
	Damage *float32 `json:"damage,omitempty"`
	Rate   *float32 `json:"rate,omitempty"`
}

// CombatDamage defines model for CombatDamage.
type CombatDamage struct {
	Ave       *float32 `json:"ave,omitempty"`
	Max       *float32 `json:"max,omitempty"`
	Min       *float32 `json:"min,omitempty"`
	SecondAve *float32 `json:"secondAve,omitempty"`
}

// CombatEnemy defines model for CombatEnemy.
type CombatEnemy struct {
	Element string   `json:"element"`
	Hp      *float32 `json:"hp,omitempty"`
	Race    string   `json:"race"`
	Size    string   `json:"size"`
	Type    string   `json:"type"`
}

// CombatIncoming defines model for CombatIncoming.
type CombatIncoming struct {
	Ave          *float32 `json:"ave,omitempty"`
	AveWithDodge *float32 `json:"aveWithDodge,omitempty"`
	Max          *float32 `json:"max,omitempty"`
	Min          *float32 `json:"min,omitempty"`
}

// CombatResults defines model for CombatResults.
type CombatResults struct {
	BattleTimeSec *float32       `json:"battleTimeSec,omitempty"`
	Crit          CombatCrit     `json:"crit"`
	Damage        CombatDamage   `json:"damage"`
	Dodge         *float32       `json:"dodge,omitempty"`
	Enemy         CombatEnemy    `json:"enemy"`
	Flee          *float32       `json:"flee,omitempty"`
	Hit           *float32       `json:"hit,omitempty"`
	Incoming      CombatIncoming `json:"incoming"`
}

// DerivedStats defines model for DerivedStats.
type DerivedStats struct {
	Aspd                float32  `json:"aspd"`
	Atk                 BasePlus `json:"atk"`
	Cri                 int      `json:"cri"`
	Def                 HardSoft `json:"def"`
	Flee                int      `json:"flee"`
	Hit                 int      `json:"hit"`
	Matk                MinMax   `json:"matk"`
	MaxHp               int      `json:"maxHp"`
	MaxSp               int      `json:"maxSp"`
	Mdef                HardSoft `json:"mdef"`
	StatPointsRemaining int      `json:"statPointsRemaining"`
}

// EnrichedBuild defines model for EnrichedBuild.
type EnrichedBuild struct {
	Alternatives   *[]EnrichedTrajectory `json:"alternatives,omitempty"`
	CalcVersion    *string               `json:"calc_version,omitempty"`
	CatalogVersion *int                  `json:"catalog_version,omitempty"`
	Class          string                `json:"class"`
	CreatedAt      time.Time             `json:"created_at"`
	Description    *string               `json:"description,omitempty"`
	FinalText      *string               `json:"final_text,omitempty"`
	GateSummary    GateSummary           `json:"gate_summary"`
	Id             string                `json:"id"`
	Mode           string                `json:"mode"`
	Playstyle      string                `json:"playstyle"`
	Primary        EnrichedTrajectory    `json:"primary"`
	Server         string                `json:"server"`
}

// EnrichedEquipSpec defines model for EnrichedEquipSpec.
type EnrichedEquipSpec struct {
	Cards *[]NamedRef `json:"cards,omitempty"`

	// Item Resolved id reference: every numeric id in a snapshot's
	// equipment, cards, or leveling target ships with its catalog
	// name inline. name is empty when the catalog has no record for
	// id, or when the API has no catalog configured.
	Item   NamedRef `json:"item"`
	Refine *int     `json:"refine,omitempty"`
}

// EnrichedSnapshot defines model for EnrichedSnapshot.
type EnrichedSnapshot struct {
	Class string `json:"class"`

	// Equipment keyed by SlotKey enum (weapon, headTop, ...)
	Equipment      *map[string]EnrichedEquipSpec `json:"equipment,omitempty"`
	Gates          *[]GateResult                 `json:"gates,omitempty"`
	Level          Level                         `json:"level"`
	LevelingTarget *struct {
		// Target Resolved id reference: every numeric id in a snapshot's
		// equipment, cards, or leveling target ships with its catalog
		// name inline. name is empty when the catalog has no record for
		// id, or when the API has no catalog configured.
		Target *NamedRef `json:"target,omitempty"`
	} `json:"leveling_target,omitempty"`
	Notes       *string        `json:"notes,omitempty"`
	PostRebirth *bool          `json:"post_rebirth,omitempty"`
	Score       *ScoreResponse `json:"score,omitempty"`
	Skills      *[]struct {
		Id    int    `json:"id"`
		Level int    `json:"level"`
		Name  string `json:"name"`
	} `json:"skills,omitempty"`
	Stats Stats `json:"stats"`
}

// EnrichedTrajectory defines model for EnrichedTrajectory.
type EnrichedTrajectory struct {
	Class     string             `json:"class"`
	Snapshots []EnrichedSnapshot `json:"snapshots"`
}

// EquipSpec defines model for EquipSpec.
type EquipSpec struct {
	Cards  *[]int `json:"cards,omitempty"`
	Id     int    `json:"id"`
	Refine *int   `json:"refine,omitempty"`
}

// EquipmentMap keyed by SlotKey enum (weapon, headTop, ...)
type EquipmentMap map[string]EquipSpec

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	Error string `json:"error"`
}

// GateOverrides defines model for GateOverrides.
type GateOverrides struct {
	IgnoreStatus *[]string `json:"ignore_status,omitempty"`
}

// GateResult defines model for GateResult.
type GateResult struct {
	// Actual any (number
	Actual   interface{}        `json:"actual,omitempty"`
	Name     string             `json:"name"`
	Reason   *string            `json:"reason,omitempty"`
	Severity GateResultSeverity `json:"severity"`

	// Threshold any (number
	Threshold interface{} `json:"threshold,omitempty"`
}

// GateResultSeverity defines model for GateResult.Severity.
type GateResultSeverity string

// GateSummary defines model for GateSummary.
type GateSummary struct {
	Fail     int `json:"fail"`
	FailHard int `json:"fail_hard"`
	Pass     int `json:"pass"`
	Warn     int `json:"warn"`
}

// GenerateEnqueueResponse defines model for GenerateEnqueueResponse.
type GenerateEnqueueResponse struct {
	// Id identifier for the enqueued generation; used as both the polling key and the eventual /builds/{id} key
	Id string `json:"id"`
}

// GenerateRequest defines model for GenerateRequest.
type GenerateRequest struct {
	// Class shim-contract class name; required
	Class string `json:"class"`

	// Description free-form scenario context (LLM treats as informational only)
	Description   *string                   `json:"description,omitempty"`
	GateOverrides *GateOverrides            `json:"gate_overrides,omitempty"`
	Mode          *GenerateRequestMode      `json:"mode,omitempty"`
	Playstyle     *GenerateRequestPlaystyle `json:"playstyle,omitempty"`
	Server        *string                   `json:"server,omitempty"`
}

// GenerateRequestMode defines model for GenerateRequest.Mode.
type GenerateRequestMode string

// GenerateRequestPlaystyle defines model for GenerateRequest.Playstyle.
type GenerateRequestPlaystyle string

// GenerationStatus defines model for GenerationStatus.
type GenerationStatus struct {
	// BuildId present only when status=completed; always equal to id
	BuildId     *string    `json:"build_id,omitempty"`
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`

	// Error present only when status=failed; generic user-facing message
	Error     *string                `json:"error,omitempty"`
	Id        string                 `json:"id"`
	StartedAt *time.Time             `json:"started_at,omitempty"`
	Status    GenerationStatusStatus `json:"status"`
}

// GenerationStatusStatus defines model for GenerationStatus.Status.
type GenerationStatusStatus string

// HardSoft defines model for HardSoft.
type HardSoft struct {
	Hard int `json:"hard"`
	Soft int `json:"soft"`
}

// Level defines model for Level.
type Level struct {
	Base int `json:"base"`
	Job  int `json:"job"`
}

// ListBuildsResponse defines model for ListBuildsResponse.
type ListBuildsResponse struct {
	Builds []BuildSummary `json:"builds"`
}

// MinMax defines model for MinMax.
type MinMax struct {
	Max int `json:"max"`
	Min int `json:"min"`
}

// NamedRef Resolved id reference: every numeric id in a snapshot's
// equipment, cards, or leveling target ships with its catalog
// name inline. name is empty when the catalog has no record for
// id, or when the API has no catalog configured.
type NamedRef struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

// Scenario defines model for Scenario.
type Scenario struct {
	// Target iRO mob id; 0 means no combat sim
	Target *int `json:"target,omitempty"`
}

// ScoreRequestBody defines model for ScoreRequestBody.
type ScoreRequestBody struct {
	Build    Build     `json:"build"`
	Scenario *Scenario `json:"scenario,omitempty"`
}

// ScoreResponse defines model for ScoreResponse.
type ScoreResponse struct {
	// CalcVersion engine snapshot stamp (backend name + data snapshot date)
	CalcVersion string         `json:"calc_version"`
	Combat      *CombatResults `json:"combat,omitempty"`
	Derived     DerivedStats   `json:"derived"`
}

// SkillAlloc defines model for SkillAlloc.
type SkillAlloc struct {
	Id    int `json:"id"`
	Level int `json:"level"`
}

// SlotKey defines model for SlotKey.
type SlotKey string

// Stats defines model for Stats.
type Stats struct {
	Agi int `json:"agi"`
	Dex int `json:"dex"`
	Int int `json:"int"`
	Luk int `json:"luk"`
	Str int `json:"str"`
	Vit int `json:"vit"`
}

// ListBuildsParams defines parameters for ListBuilds.
type ListBuildsParams struct {
	// Class filter to one class (e.g. "taekwon_kid")
	Class *string `form:"class,omitempty" json:"class,omitempty"`

	// Server filter to one server profile (e.g. "uaro")
	Server *string `form:"server,omitempty" json:"server,omitempty"`

	// Limit cap results (default 5, max 50)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GenerateJSONRequestBody defines body for Generate for application/json ContentType.
type GenerateJSONRequestBody = GenerateRequest

// ScoreJSONRequestBody defines body for Score for application/json ContentType.
type ScoreJSONRequestBody = ScoreRequestBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List saved trajectories (recency-ordered)
	// (GET /builds)
	ListBuilds(w http.ResponseWriter, r *http.Request, params ListBuildsParams)
	// Fetch one saved trajectory with catalog names resolved
	// (GET /builds/{id})
	GetBuild(w http.ResponseWriter, r *http.Request, id string)
	// Enqueue an asynchronous build-generation job
	// (POST /generate)
	Generate(w http.ResponseWriter, r *http.Request)
	// Poll status of an enqueued generation
	// (GET /generations/{id})
	GetGeneration(w http.ResponseWriter, r *http.Request, id string)
	// Score a fully-specified build
	// (POST /score)
	Score(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListBuilds operation middleware
func (siw *ServerInterfaceWrapper) ListBuilds(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBuildsParams

	// ------------- Optional query parameter "class" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "class", r.URL.Query(), &params.Class, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "class"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "class", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "server" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "server", r.URL.Query(), &params.Server, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "server"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "server", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBuilds(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBuild operation middleware
func (siw *ServerInterfaceWrapper) GetBuild(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBuild(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Generate operation middleware
func (siw *ServerInterfaceWrapper) Generate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Generate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGeneration operation middleware
func (siw *ServerInterfaceWrapper) GetGeneration(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGeneration(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Score operation middleware
func (siw *ServerInterfaceWrapper) Score(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Score(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/builds", wrapper.ListBuilds)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/builds/{id}", wrapper.GetBuild)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/generate", wrapper.Generate)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/generations/{id}", wrapper.GetGeneration)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/score", wrapper.Score)

	return m
}

type ListBuildsRequestObject struct {
	Params ListBuildsParams
}

type ListBuildsResponseObject interface {
	VisitListBuildsResponse(w http.ResponseWriter) error
}

type ListBuilds200JSONResponse ListBuildsResponse

func (response ListBuilds200JSONResponse) VisitListBuildsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListBuilds400JSONResponse ErrorBody

func (response ListBuilds400JSONResponse) VisitListBuildsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListBuilds500JSONResponse ErrorBody

func (response ListBuilds500JSONResponse) VisitListBuildsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetBuildRequestObject struct {
	Id string `json:"id"`
}

type GetBuildResponseObject interface {
	VisitGetBuildResponse(w http.ResponseWriter) error
}

type GetBuild200JSONResponse EnrichedBuild

func (response GetBuild200JSONResponse) VisitGetBuildResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetBuild400JSONResponse ErrorBody

func (response GetBuild400JSONResponse) VisitGetBuildResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetBuild404JSONResponse ErrorBody

func (response GetBuild404JSONResponse) VisitGetBuildResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetBuild500JSONResponse ErrorBody

func (response GetBuild500JSONResponse) VisitGetBuildResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GenerateRequestObject struct {
	Body *GenerateJSONRequestBody
}

type GenerateResponseObject interface {
	VisitGenerateResponse(w http.ResponseWriter) error
}

type Generate202JSONResponse GenerateEnqueueResponse

func (response Generate202JSONResponse) VisitGenerateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type Generate400JSONResponse ErrorBody

func (response Generate400JSONResponse) VisitGenerateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Generate429JSONResponse ErrorBody

func (response Generate429JSONResponse) VisitGenerateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type Generate503ResponseHeaders struct {
	RetryAfter *int
}

type Generate503JSONResponse struct {
	Body    ErrorBody
	Headers Generate503ResponseHeaders
}

func (response Generate503JSONResponse) VisitGenerateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetGenerationRequestObject struct {
	Id string `json:"id"`
}

type GetGenerationResponseObject interface {
	VisitGetGenerationResponse(w http.ResponseWriter) error
}

type GetGeneration200JSONResponse GenerationStatus

func (response GetGeneration200JSONResponse) VisitGetGenerationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetGeneration404JSONResponse ErrorBody

func (response GetGeneration404JSONResponse) VisitGetGenerationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetGeneration500JSONResponse ErrorBody

func (response GetGeneration500JSONResponse) VisitGetGenerationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ScoreRequestObject struct {
	Body *ScoreJSONRequestBody
}

type ScoreResponseObject interface {
	VisitScoreResponse(w http.ResponseWriter) error
}

type Score200JSONResponse ScoreResponse

func (response Score200JSONResponse) VisitScoreResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Score400JSONResponse ErrorBody

func (response Score400JSONResponse) VisitScoreResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Score500JSONResponse ErrorBody

func (response Score500JSONResponse) VisitScoreResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type Score502JSONResponse ErrorBody

func (response Score502JSONResponse) VisitScoreResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List saved trajectories (recency-ordered)
	// (GET /builds)
	ListBuilds(ctx context.Context, request ListBuildsRequestObject) (ListBuildsResponseObject, error)
	// Fetch one saved trajectory with catalog names resolved
	// (GET /builds/{id})
	GetBuild(ctx context.Context, request GetBuildRequestObject) (GetBuildResponseObject, error)
	// Enqueue an asynchronous build-generation job
	// (POST /generate)
	Generate(ctx context.Context, request GenerateRequestObject) (GenerateResponseObject, error)
	// Poll status of an enqueued generation
	// (GET /generations/{id})
	GetGeneration(ctx context.Context, request GetGenerationRequestObject) (GetGenerationResponseObject, error)
	// Score a fully-specified build
	// (POST /score)
	Score(ctx context.Context, request ScoreRequestObject) (ScoreResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListBuilds operation middleware
func (sh *strictHandler) ListBuilds(w http.ResponseWriter, r *http.Request, params ListBuildsParams) {
	var request ListBuildsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListBuilds(ctx, request.(ListBuildsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListBuilds")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListBuildsResponseObject); ok {
		if err := validResponse.VisitListBuildsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetBuild operation middleware
func (sh *strictHandler) GetBuild(w http.ResponseWriter, r *http.Request, id string) {
	var request GetBuildRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBuild(ctx, request.(GetBuildRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBuild")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBuildResponseObject); ok {
		if err := validResponse.VisitGetBuildResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Generate operation middleware
func (sh *strictHandler) Generate(w http.ResponseWriter, r *http.Request) {
	var request GenerateRequestObject

	var body GenerateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Generate(ctx, request.(GenerateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Generate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GenerateResponseObject); ok {
		if err := validResponse.VisitGenerateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGeneration operation middleware
func (sh *strictHandler) GetGeneration(w http.ResponseWriter, r *http.Request, id string) {
	var request GetGenerationRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGeneration(ctx, request.(GetGenerationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGeneration")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGenerationResponseObject); ok {
		if err := validResponse.VisitGetGenerationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Score operation middleware
func (sh *strictHandler) Score(w http.ResponseWriter, r *http.Request) {
	var request ScoreRequestObject

	var body ScoreJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Score(ctx, request.(ScoreRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Score")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ScoreResponseObject); ok {
		if err := validResponse.VisitScoreResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFttbxs3Ev4rg70DzkbXsuIkQM/GfUhStw3qNIaVojhUgUEtR1rGXHJDcmWrge/j/YD7ifdLDnzZF2m5",
	"lpQmvuZLtFqSMxzOy/MM5U9JJotSChRGJ6efEp3lWBD38SXReMkr97lUskRlGLqnGdFo/zerEpPThAmD",
	"C1TJfZqUYfzmm/s0UfixYgppcvqbXyCMfp/Wo+XsA2bGLvOyYpz25WacaPeBos4UKw2TIjlNdM6Ko0wK",
	"o0hmwA0CQQqEg2ki5JJlOE1SmCaG4M2tFNc3jNovRqPRYdII10YxsbDCrZ5lgcJYSX9VOE9Ok78ct2Y6",
	"DjY6Pq8HviGlnchxiXzbpAs36D5NCkmxvxcp+AqmSanwSKHAW8KnCTANWaUUCsNXoKuylMogTdIERVVY",
	"e3aGJ9bS/tP7yOY0qiWqzhF1XhnifeAh9Sdu0H2aGOaXqVWYVXSBxkknnGnDMqcfXZACI5psOIQ3Xa3D",
	"oEtMqqIgavWAZ/R2lSkkBuk1ccc5l6qwnxJKDB4ZVmDMA9aOJLLmghi81q0uDxnsB2KwVvs+TRiNrlhy",
	"stJmxTF+MkOHtmFFZn2is+E02KVZoStoYxsxm7+SxYyYV4qZvsUpKcjCqSsqzsnMqm5Uhc0yoipmPiko",
	"YnYZeD+owXeNrHUdyHI3BQpyt9s4JnYapzGTgr5Y/rFdnQssIq6MHOvk03OEvNzR4NmAI7Hf4y/8F9v8",
	"y62bNhqG9cLsYQd6LTJZ2PU++wDJEn9lJv9O0sX/48SHz/AKdcVNtEQaw/EdK3CC2U6qZCHMHkomnYC0",
	"aaoJi+1zQgjZWTsbEWsH3b689+X7NJlz3G3x3O926zjWcZ7tejSutum6wVbBzJ1l623G3Pc7VGyJdFIX",
	"xg3n1WU3mXe81dxs07bBVv7g42CK2vkPr/MjUXQi56Zr+v5Cwdb9F8UOqr5h4g25C0H1Yzm00N1k6NWe",
	"27AQ4FIyYfQVFoSJcPZbEGXuTtWZwFvUH0PYordl0CX1J1fvp1Y+LjnmFudCsSxHOoBSCTeoBDFs6Z+Z",
	"wWIrrqrXfKeIFSM9WgiiiVLEPWeEZ9dLVHoImWTEEC4XkTGdE3lcsDRngvBrg3fmkbBUDaz3BFmlYrvo",
	"ED+or4TQ3FZa1XaAbLV6jptMSl97NrAyUXR3x/yZFEivcB5zR7vAPvMVzplw1i/IHSsscXgydkXYP4zT",
	"bWHuJD6074kgpc6l2YcirBE+Qimzvkz45dr0XXyiNfpmXCQ3uEIKsxVMuDQ/4Qosb4KDWySlFCnkSOg7",
	"WW6S0nZ/9uB3PzQbKB6axI5tP57qRjOxuDZEWYbXM2z7/W5+EENTQobt9cNSanOtcMaUyTsDZlJyJMLF",
	"XibVVhQ0sYOuUJdSaAeD9A3jfN2i69tayy6d7NlYr/9KWK67Ww5wQ+vFYg69eWj7sPMNgXWK2U6yI8lt",
	"jzjSIfb2r3pN1PY2PrCVVlR0G/skv/4x9tLcgCd8gXRGh/WvG0ufm5O+Xi46V0qql5LGyKt9tT0E/LDY",
	"1m3mertEpRjFWFAuhFR4bT24ih7jJqXt+FFUVsiSfRCXmYrwfn+OiBUcBKifJpxpc5icWhKT1qLd03Ay",
	"cA0yPYCVNC5RMbPqNtZK7/G3RAmLcAnj4b/rnCgabfKZXKHOpQenn6f/xoGFdNXoN3R0gw06p3c0itqt",
	"xDvK69mm88ZZZDsz2Nl+nZ2gQEUMnouPFVZt2RioEesWZhSFYXOGCuZSgckR0K9DYeEXZlKcQaWRAtEw",
	"kyZ3o0rJbZ2FG1wBEdTPXKKwjgjHM0s29PEnRu/tiCTdXmUe2toVfqxQmz/cYz+DRuh2brC+5FwhHlmO",
	"ATpDQRSTYAXgnYGDi4s3YCxM1tZETHgq4lIgSMFXh562XaBYWFhwMh6P0wFuIbvZZBtoalNPh0js32Vf",
	"YxrN9GVhsfzSUs0Z4URkSK9p5RZrnr2H2Ljcr30frZMPOACTYtIk0Y3WlfW065hrlwo1CuNOAG5zFOAT",
	"8T+sNTkapGdA+C1ZacCP1muNBBZ1jGbCXlTzc+hpU5F23IrNDHYf7iBYZsNUHc1JZiOzQK19F6knZoCL",
	"akPUvhq3xa32HJ89rM9VQvimVWPAkMyQbr9kcUcRVl8zZsxPmpZMzz+Gc7UO47f1auwCYXRM9EWNsHe9",
	"dfwgZ7tfOtrBUalMG9fR0cP53ifhneHt2p3VNmgb1o6pFlpwPXVClzvSc2O7VEY7yrfKY0IbwtaLnSvU",
	"ki+RAqOgcI4KRYantlapFYiqcHHDKDABBGqk/jc9FQ3RTsHh8BSkgppfgueRoHNWarhlJgdmNISO1lS4",
	"G10mOBM48te7TAMWpQnxa8tlGAw50SAkKMykorYMTwWjTloz9MXl63pYPSuTYs4WlUI6mgrXdtmFD+5L",
	"+mK2noQC+BC53kAZV2+hkDNg9AzGUCARfiuuCw6aFUmUfEQkO17swEAc0s/qLudWT/dkvN3Jw3w8jIuG",
	"wYCRuhQ+wuzWe6Pr9kKxYAIbb7TZvijhYEayGxTU+9M3QIlpPdY+4eFA9ZqRHS9r6hsih4bcdcK2eWu3",
	"Dr17jLDGRi84aq8bxvkLzmX2BZobMXcebl4EYtmtYZ5dJmkS6GX49MatZD+9lO5GMWfI7VdEFVK5jqcK",
	"l41zKc0Cif2SZBlqLdXqSffhJAqZhm5vFoO3LgNJlYmBWxRe3QzUQ6PiL5Zslzppp6dOUT/Dq+A19FL7",
	"tr93is5lJGuThSBK3sBbl0PhoANnD8GFHcjSsIL9jmo0FVPxvawUoKCluxM5nQqAI7h8O3kHx67nBu0/",
	"yhRaXkB4dgbzivPVkS4xszSIgksO8N9//weC9zqspeEbJ89h+jZvdaUEutQIurh4c0TtCuKs5lRAOqQK",
	"PsiZJSSmUkLDyfgEvgFLmPyaP5y/g2ZNJkUgU5Z2BfAHcg5ExOhadwVfqNu9l2TBhIVSYGG7XUMTu0lT",
	"N9EY6v58L9z+kwKdyTanreoiiMWx61a6LKVBhfJrj+hdjh0z1WdVczJtLXb94vL19U/n/wRimsJXKmlj",
	"ZgS/MpPLygAz6VS0C9UmfD5+CgcTVEuWIfwiyJIwd1t7eFa7gGVsTFSoLda/lerGec6rhh9qIAphnT36",
	"2NQP/zxrKqZJzhb59S37nSg6TQ5H8HODLfyyQhqw0V9a43e2N5OVoEStfBk3zFgilih55EyPyg6yMVUX",
	"i2Q8ejIa28CUJQpSsuQ0eToaj55aEEBM7hLGcQv+QkW26cR5x2uanHbwo5ulSIEGlU5Of+sRX8YNKmsw",
	"e/SeSx/gaDHaNMKhC/nk1BIAd/3jsUbbBXUVIwo+HpbpaaR1gznj2AiviJLDUpsbqj3EZqS0/morIBxQ",
	"nJOKG3ieQkHu4Pl4SBJnhUt3raCmwfq822B9EsE4720O9RjBndXJeOzQgRSmvuEpS84yd3DHH0InrpX0",
	"4J1InyK4hLu+54uQBTqB7G/smG8rPPuCGrWt2Igir8WScEbBWRcal7Q6PH8sHS7YTBG1gmNAkUmKYMlq",
	"pdAVu+ba19usnzbhQGGGIlsdSUVRIT1087opdDAef0B/Vtui0ZEYm+58T7xNggdSNcneN0qDt9qU0Dqr",
	"AzBt2fY/YxkOka/pn+s/TIicxiRaYdBNcyjrMd2TUbCWbB0TCqZ1QG3Pxs8eR4ufZc8eJicGGP0zxsn3",
	"aLLcp/DoUdZUdh0p+KCpHdthYakjpDL0u3UPVLl+dA0KWFEgZcQgX43gUnLeIocWVVXCsAZWMQ3TtmM1",
	"TSwRn4a21TQZTcUVZrIoUFCkHo9lhPqmwr+ejsH/3FKPvgDgmYoO4gGTM91dowU9df/d7p1pEGjLZY0L",
	"PazYzDbBuD4XdNj0F/Gdzbb9/TpXsEnnvpdYTr64+M0LkYgjt/3lxl5n/kz7TjKXKrjIoyaeYERw1dGr",
	"6n0RDgpJ8bjp3h935h06FU/+/jgqdqwYaI4lVyXJmFn5vPT0cRSxwcM06LwyhokFUHkrHMVSK+DEODxo",
	"2burrZ+SK/vi6MXc+EuKXhlscdr9emI7r+mcAKJXIsuVFLLSnpcerWejtXTWeNNDQKA1Zx8N/LlLeu+6",
	"5mFn6UbTIxXQX8SNkLfiT1owL3dh996hmt8RxYvjK8Kzo9DnsO4ygleEc1TuD3K4Bav+qtcwhaHlceCI",
	"Wupb3OlUuLZHCk0b/PDMzdGMYkYcHaNVhnqjTUIETYHNgUxF3TUdvfO9cqZhwZYoUiCdFgqQBWFCGw9k",
	"CjmLFSzXTf1K1arXVN6pXI2/tPzhIvVKFmVlrIWdFR6z+HjP6JceWwqDHyj0f+AFBJ7d3cFB5vzsaM7u",
	"XO/lUcPsF4F3JWZWG5u7lSC8jjQ4MIoIbXVNQxAG3U4eR7dJ317Prb1qO2aK6ByOXfcJSiJYdriRHZyj",
	"AOl1LGctgfJdjxhxvJAZ4UBtbMsy9KgrxZPTJDemPD0+5nZALrU5/Xb87Ti5f3//vwAAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
