//go:build go1.22

// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for BuildMode.
const (
	BuildModePreRenewal BuildMode = "pre-renewal"
	BuildModeRenewal    BuildMode = "renewal"
)

// Valid indicates whether the value is a known member of the BuildMode enum.
func (e BuildMode) Valid() bool {
	switch e {
	case BuildModePreRenewal:
		return true
	case BuildModeRenewal:
		return true
	default:
		return false
	}
}

// Defines values for BuildTier.
const (
	Budget    BuildTier = "budget"
	Endgame   BuildTier = "endgame"
	Realistic BuildTier = "realistic"
)

// Valid indicates whether the value is a known member of the BuildTier enum.
func (e BuildTier) Valid() bool {
	switch e {
	case Budget:
		return true
	case Endgame:
		return true
	case Realistic:
		return true
	default:
		return false
	}
}

// Defines values for GateResultSeverity.
const (
	Fail     GateResultSeverity = "fail"
	FailHard GateResultSeverity = "fail_hard"
	Pass     GateResultSeverity = "pass"
	Warn     GateResultSeverity = "warn"
)

// Valid indicates whether the value is a known member of the GateResultSeverity enum.
func (e GateResultSeverity) Valid() bool {
	switch e {
	case Fail:
		return true
	case FailHard:
		return true
	case Pass:
		return true
	case Warn:
		return true
	default:
		return false
	}
}

// Defines values for GenerateRequestMode.
const (
	GenerateRequestModePreRenewal GenerateRequestMode = "pre-renewal"
	GenerateRequestModeRenewal    GenerateRequestMode = "renewal"
)

// Valid indicates whether the value is a known member of the GenerateRequestMode enum.
func (e GenerateRequestMode) Valid() bool {
	switch e {
	case GenerateRequestModePreRenewal:
		return true
	case GenerateRequestModeRenewal:
		return true
	default:
		return false
	}
}

// Defines values for GenerateRequestPlaystyle.
const (
	BalancedDual       GenerateRequestPlaystyle = "balanced_dual"
	BalancedGeneralist GenerateRequestPlaystyle = "balanced_generalist"
	Pvm                GenerateRequestPlaystyle = "pvm"
	Pvp                GenerateRequestPlaystyle = "pvp"
)

// Valid indicates whether the value is a known member of the GenerateRequestPlaystyle enum.
func (e GenerateRequestPlaystyle) Valid() bool {
	switch e {
	case BalancedDual:
		return true
	case BalancedGeneralist:
		return true
	case Pvm:
		return true
	case Pvp:
		return true
	default:
		return false
	}
}

// Defines values for GenerationStatusStatus.
const (
	Completed GenerationStatusStatus = "completed"
	Failed    GenerationStatusStatus = "failed"
	Queued    GenerationStatusStatus = "queued"
	Running   GenerationStatusStatus = "running"
)

// Valid indicates whether the value is a known member of the GenerationStatusStatus enum.
func (e GenerationStatusStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case Failed:
		return true
	case Queued:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// Defines values for SlotKey.
const (
	Accessory1 SlotKey = "accessory1"
	Accessory2 SlotKey = "accessory2"
	Armor      SlotKey = "armor"
	Footgear   SlotKey = "footgear"
	Garment    SlotKey = "garment"
	HeadBot    SlotKey = "headBot"
	HeadMid    SlotKey = "headMid"
	HeadTop    SlotKey = "headTop"
	Shield     SlotKey = "shield"
	Weapon     SlotKey = "weapon"
)

// Valid indicates whether the value is a known member of the SlotKey enum.
func (e SlotKey) Valid() bool {
	switch e {
	case Accessory1:
		return true
	case Accessory2:
		return true
	case Armor:
		return true
	case Footgear:
		return true
	case Garment:
		return true
	case HeadBot:
		return true
	case HeadMid:
		return true
	case HeadTop:
		return true
	case Shield:
		return true
	case Weapon:
		return true
	default:
		return false
	}
}

// AcceptBuildResponse defines model for AcceptBuildResponse.
type AcceptBuildResponse struct {
	AcceptedAt time.Time `json:"accepted_at"`
	Id         string    `json:"id"`
}

// BasePlus defines model for BasePlus.
type BasePlus struct {
	Base int `json:"base"`
	Plus int `json:"plus"`
}

// Build defines model for Build.
type Build struct {
	// Class shim-contract class name ("novice", "taekwon_kid", ...)
	Class *string `json:"class,omitempty"`

	// Equipment keyed by SlotKey enum (weapon, headTop, ...)
	Equipment *EquipmentMap `json:"equipment,omitempty"`
	Level     Level         `json:"level"`

	// Mode only "pre-renewal" is currently supported
	Mode   *BuildMode `json:"mode,omitempty"`
	Server *string    `json:"server,omitempty"`
	Stats  Stats      `json:"stats"`
	Tier   *BuildTier `json:"tier,omitempty"`
}

// BuildMode only "pre-renewal" is currently supported
type BuildMode string

// BuildTier defines model for Build.Tier.
type BuildTier string

// BuildSummary defines model for BuildSummary.
type BuildSummary struct {
	// AcceptedAt when the build was user-accepted; absent = pending (not RAG-visible)
	AcceptedAt  *time.Time  `json:"accepted_at,omitempty"`
	Class       string      `json:"class"`
	CreatedAt   time.Time   `json:"created_at"`
	Description *string     `json:"description,omitempty"`
	GateSummary GateSummary `json:"gate_summary"`
	Id          string      `json:"id"`
	Playstyle   string      `json:"playstyle"`
	Server      string      `json:"server"`
}

// CombatCrit defines model for CombatCrit.
type CombatCrit struct {
	Damage *float32 `json:"damage,omitempty"`
	Rate   *float32 `json:"rate,omitempty"`
}

// CombatDamage defines model for CombatDamage.
type CombatDamage struct {
	Ave       *float32 `json:"ave,omitempty"`
	Max       *float32 `json:"max,omitempty"`
	Min       *float32 `json:"min,omitempty"`
	SecondAve *float32 `json:"secondAve,omitempty"`
}

// CombatEnemy defines model for CombatEnemy.
type CombatEnemy struct {
	Element string   `json:"element"`
	Hp      *float32 `json:"hp,omitempty"`
	Race    string   `json:"race"`
	Size    string   `json:"size"`
	Type    string   `json:"type"`
}

// CombatIncoming defines model for CombatIncoming.
type CombatIncoming struct {
	Ave          *float32 `json:"ave,omitempty"`
	AveWithDodge *float32 `json:"aveWithDodge,omitempty"`
	Max          *float32 `json:"max,omitempty"`
	Min          *float32 `json:"min,omitempty"`
}

// CombatResults defines model for CombatResults.
type CombatResults struct {
	BattleTimeSec *float32       `json:"battleTimeSec,omitempty"`
	Crit          CombatCrit     `json:"crit"`
	Damage        CombatDamage   `json:"damage"`
	Dodge         *float32       `json:"dodge,omitempty"`
	Enemy         CombatEnemy    `json:"enemy"`
	Flee          *float32       `json:"flee,omitempty"`
	Hit           *float32       `json:"hit,omitempty"`
	Incoming      CombatIncoming `json:"incoming"`
}

// DerivedStats defines model for DerivedStats.
type DerivedStats struct {
	Aspd                float32  `json:"aspd"`
	Atk                 BasePlus `json:"atk"`
	Cri                 int      `json:"cri"`
	Def                 HardSoft `json:"def"`
	Flee                int      `json:"flee"`
	Hit                 int      `json:"hit"`
	Matk                MinMax   `json:"matk"`
	MaxHp               int      `json:"maxHp"`
	MaxSp               int      `json:"maxSp"`
	Mdef                HardSoft `json:"mdef"`
	StatPointsRemaining int      `json:"statPointsRemaining"`
}

// EnrichedBuild defines model for EnrichedBuild.
type EnrichedBuild struct {
	// AcceptedAt when the build was user-accepted; absent = pending (not RAG-visible)
	AcceptedAt     *time.Time            `json:"accepted_at,omitempty"`
	Alternatives   *[]EnrichedTrajectory `json:"alternatives,omitempty"`
	CalcVersion    *string               `json:"calc_version,omitempty"`
	CatalogVersion *int                  `json:"catalog_version,omitempty"`
	Class          string                `json:"class"`
	CreatedAt      time.Time             `json:"created_at"`
	Description    *string               `json:"description,omitempty"`
	FinalText      *string               `json:"final_text,omitempty"`
	GateSummary    GateSummary           `json:"gate_summary"`
	Id             string                `json:"id"`
	Mode           string                `json:"mode"`
	Playstyle      string                `json:"playstyle"`
	Primary        EnrichedTrajectory    `json:"primary"`
	Server         string                `json:"server"`
}

// EnrichedEquipSpec defines model for EnrichedEquipSpec.
type EnrichedEquipSpec struct {
	Cards *[]NamedRef `json:"cards,omitempty"`

	// Item Resolved id reference: every numeric id in a snapshot's
	// equipment, cards, or leveling target ships with its catalog
	// name inline. name is empty when the catalog has no record for
	// id, or when the API has no catalog configured.
	Item   NamedRef `json:"item"`
	Refine *int     `json:"refine,omitempty"`
}

// EnrichedSnapshot defines model for EnrichedSnapshot.
type EnrichedSnapshot struct {
	Class string `json:"class"`

	// Equipment keyed by SlotKey enum (weapon, headTop, ...)
	Equipment      *map[string]EnrichedEquipSpec `json:"equipment,omitempty"`
	Gates          *[]GateResult                 `json:"gates,omitempty"`
	Level          Level                         `json:"level"`
	LevelingTarget *struct {
		// Target Resolved id reference: every numeric id in a snapshot's
		// equipment, cards, or leveling target ships with its catalog
		// name inline. name is empty when the catalog has no record for
		// id, or when the API has no catalog configured.
		Target *NamedRef `json:"target,omitempty"`
	} `json:"leveling_target,omitempty"`
	Notes       *string        `json:"notes,omitempty"`
	PostRebirth *bool          `json:"post_rebirth,omitempty"`
	Score       *ScoreResponse `json:"score,omitempty"`
	Skills      *[]struct {
		Id    int    `json:"id"`
		Level int    `json:"level"`
		Name  string `json:"name"`
	} `json:"skills,omitempty"`
	Stats Stats `json:"stats"`
}

// EnrichedTrajectory defines model for EnrichedTrajectory.
type EnrichedTrajectory struct {
	Class     string             `json:"class"`
	Snapshots []EnrichedSnapshot `json:"snapshots"`
}

// EquipSpec defines model for EquipSpec.
type EquipSpec struct {
	Cards  *[]int `json:"cards,omitempty"`
	Id     int    `json:"id"`
	Refine *int   `json:"refine,omitempty"`
}

// EquipmentMap keyed by SlotKey enum (weapon, headTop, ...)
type EquipmentMap map[string]EquipSpec

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	Error string `json:"error"`
}

// GateOverrides defines model for GateOverrides.
type GateOverrides struct {
	IgnoreStatus *[]string `json:"ignore_status,omitempty"`
}

// GateResult defines model for GateResult.
type GateResult struct {
	// Actual any (number
	Actual   interface{}        `json:"actual,omitempty"`
	Name     string             `json:"name"`
	Reason   *string            `json:"reason,omitempty"`
	Severity GateResultSeverity `json:"severity"`

	// Threshold any (number
	Threshold interface{} `json:"threshold,omitempty"`
}

// GateResultSeverity defines model for GateResult.Severity.
type GateResultSeverity string

// GateSummary defines model for GateSummary.
type GateSummary struct {
	Fail     int `json:"fail"`
	FailHard int `json:"fail_hard"`
	Pass     int `json:"pass"`
	Warn     int `json:"warn"`
}

// GenerateEnqueueResponse defines model for GenerateEnqueueResponse.
type GenerateEnqueueResponse struct {
	// Id identifier for the enqueued generation; used as both the polling key and the eventual /builds/{id} key
	Id string `json:"id"`
}

// GenerateRequest defines model for GenerateRequest.
type GenerateRequest struct {
	// Class shim-contract class name; required
	Class string `json:"class"`

	// Description free-form scenario context (LLM treats as informational only)
	Description   *string                   `json:"description,omitempty"`
	GateOverrides *GateOverrides            `json:"gate_overrides,omitempty"`
	Mode          *GenerateRequestMode      `json:"mode,omitempty"`
	Playstyle     *GenerateRequestPlaystyle `json:"playstyle,omitempty"`
	Server        *string                   `json:"server,omitempty"`
}

// GenerateRequestMode defines model for GenerateRequest.Mode.
type GenerateRequestMode string

// GenerateRequestPlaystyle defines model for GenerateRequest.Playstyle.
type GenerateRequestPlaystyle string

// GenerationStatus defines model for GenerationStatus.
type GenerationStatus struct {
	// BuildId present only when status=completed; always equal to id
	BuildId     *string    `json:"build_id,omitempty"`
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`

	// Error present only when status=failed; generic user-facing message
	Error     *string                `json:"error,omitempty"`
	Id        string                 `json:"id"`
	StartedAt *time.Time             `json:"started_at,omitempty"`
	Status    GenerationStatusStatus `json:"status"`
}

// GenerationStatusStatus defines model for GenerationStatus.Status.
type GenerationStatusStatus string

// HardSoft defines model for HardSoft.
type HardSoft struct {
	Hard int `json:"hard"`
	Soft int `json:"soft"`
}

// Level defines model for Level.
type Level struct {
	Base int `json:"base"`
	Job  int `json:"job"`
}

// ListBuildsResponse defines model for ListBuildsResponse.
type ListBuildsResponse struct {
	Builds []BuildSummary `json:"builds"`
}

// MinMax defines model for MinMax.
type MinMax struct {
	Max int `json:"max"`
	Min int `json:"min"`
}

// NamedRef Resolved id reference: every numeric id in a snapshot's
// equipment, cards, or leveling target ships with its catalog
// name inline. name is empty when the catalog has no record for
// id, or when the API has no catalog configured.
type NamedRef struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

// Scenario defines model for Scenario.
type Scenario struct {
	// Target iRO mob id; 0 means no combat sim
	Target *int `json:"target,omitempty"`
}

// ScoreRequestBody defines model for ScoreRequestBody.
type ScoreRequestBody struct {
	Build    Build     `json:"build"`
	Scenario *Scenario `json:"scenario,omitempty"`
}

// ScoreResponse defines model for ScoreResponse.
type ScoreResponse struct {
	// CalcVersion engine snapshot stamp (backend name + data snapshot date)
	CalcVersion string         `json:"calc_version"`
	Combat      *CombatResults `json:"combat,omitempty"`
	Derived     DerivedStats   `json:"derived"`
}

// SkillAlloc defines model for SkillAlloc.
type SkillAlloc struct {
	Id    int `json:"id"`
	Level int `json:"level"`
}

// SlotKey defines model for SlotKey.
type SlotKey string

// Stats defines model for Stats.
type Stats struct {
	Agi int `json:"agi"`
	Dex int `json:"dex"`
	Int int `json:"int"`
	Luk int `json:"luk"`
	Str int `json:"str"`
	Vit int `json:"vit"`
}

// ListBuildsParams defines parameters for ListBuilds.
type ListBuildsParams struct {
	// Class filter to one class (e.g. "taekwon_kid")
	Class *string `form:"class,omitempty" json:"class,omitempty"`

	// Server filter to one server profile (e.g. "uaro")
	Server *string `form:"server,omitempty" json:"server,omitempty"`

	// Limit cap results (default 5, max 50)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Accepted filter by acceptance state; true = accepted only, false = pending (not yet accepted) only, omitted = all
	Accepted *bool `form:"accepted,omitempty" json:"accepted,omitempty"`
}

// GenerateJSONRequestBody defines body for Generate for application/json ContentType.
type GenerateJSONRequestBody = GenerateRequest

// ScoreJSONRequestBody defines body for Score for application/json ContentType.
type ScoreJSONRequestBody = ScoreRequestBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List saved trajectories (recency-ordered)
	// (GET /builds)
	ListBuilds(w http.ResponseWriter, r *http.Request, params ListBuildsParams)
	// Fetch one saved trajectory with catalog names resolved
	// (GET /builds/{id})
	GetBuild(w http.ResponseWriter, r *http.Request, id string)
	// Accept a saved trajectory, making it visible to RAG retrieval
	// (POST /builds/{id}/accept)
	AcceptBuild(w http.ResponseWriter, r *http.Request, id string)
	// Enqueue an asynchronous build-generation job
	// (POST /generate)
	Generate(w http.ResponseWriter, r *http.Request)
	// Poll status of an enqueued generation
	// (GET /generations/{id})
	GetGeneration(w http.ResponseWriter, r *http.Request, id string)
	// Score a fully-specified build
	// (POST /score)
	Score(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListBuilds operation middleware
func (siw *ServerInterfaceWrapper) ListBuilds(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBuildsParams

	// ------------- Optional query parameter "class" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "class", r.URL.Query(), &params.Class, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "class"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "class", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "server" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "server", r.URL.Query(), &params.Server, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "server"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "server", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "accepted" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "accepted", r.URL.Query(), &params.Accepted, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "accepted"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accepted", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBuilds(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBuild operation middleware
func (siw *ServerInterfaceWrapper) GetBuild(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBuild(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptBuild operation middleware
func (siw *ServerInterfaceWrapper) AcceptBuild(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptBuild(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Generate operation middleware
func (siw *ServerInterfaceWrapper) Generate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Generate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGeneration operation middleware
func (siw *ServerInterfaceWrapper) GetGeneration(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGeneration(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Score operation middleware
func (siw *ServerInterfaceWrapper) Score(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Score(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/builds", wrapper.ListBuilds)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/builds/{id}", wrapper.GetBuild)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/builds/{id}/accept", wrapper.AcceptBuild)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/generate", wrapper.Generate)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/generations/{id}", wrapper.GetGeneration)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/score", wrapper.Score)

	return m
}

type ListBuildsRequestObject struct {
	Params ListBuildsParams
}

type ListBuildsResponseObject interface {
	VisitListBuildsResponse(w http.ResponseWriter) error
}

type ListBuilds200JSONResponse ListBuildsResponse

func (response ListBuilds200JSONResponse) VisitListBuildsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListBuilds400JSONResponse ErrorBody

func (response ListBuilds400JSONResponse) VisitListBuildsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListBuilds500JSONResponse ErrorBody

func (response ListBuilds500JSONResponse) VisitListBuildsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetBuildRequestObject struct {
	Id string `json:"id"`
}

type GetBuildResponseObject interface {
	VisitGetBuildResponse(w http.ResponseWriter) error
}

type GetBuild200JSONResponse EnrichedBuild

func (response GetBuild200JSONResponse) VisitGetBuildResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetBuild400JSONResponse ErrorBody

func (response GetBuild400JSONResponse) VisitGetBuildResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetBuild404JSONResponse ErrorBody

func (response GetBuild404JSONResponse) VisitGetBuildResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetBuild500JSONResponse ErrorBody

func (response GetBuild500JSONResponse) VisitGetBuildResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptBuildRequestObject struct {
	Id string `json:"id"`
}

type AcceptBuildResponseObject interface {
	VisitAcceptBuildResponse(w http.ResponseWriter) error
}

type AcceptBuild200JSONResponse AcceptBuildResponse

func (response AcceptBuild200JSONResponse) VisitAcceptBuildResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptBuild404JSONResponse ErrorBody

func (response AcceptBuild404JSONResponse) VisitAcceptBuildResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type AcceptBuild500JSONResponse ErrorBody

func (response AcceptBuild500JSONResponse) VisitAcceptBuildResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GenerateRequestObject struct {
	Body *GenerateJSONRequestBody
}

type GenerateResponseObject interface {
	VisitGenerateResponse(w http.ResponseWriter) error
}

type Generate202JSONResponse GenerateEnqueueResponse

func (response Generate202JSONResponse) VisitGenerateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type Generate400JSONResponse ErrorBody

func (response Generate400JSONResponse) VisitGenerateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Generate429JSONResponse ErrorBody

func (response Generate429JSONResponse) VisitGenerateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type Generate503ResponseHeaders struct {
	RetryAfter *int
}

type Generate503JSONResponse struct {
	Body    ErrorBody
	Headers Generate503ResponseHeaders
}

func (response Generate503JSONResponse) VisitGenerateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetGenerationRequestObject struct {
	Id string `json:"id"`
}

type GetGenerationResponseObject interface {
	VisitGetGenerationResponse(w http.ResponseWriter) error
}

type GetGeneration200JSONResponse GenerationStatus

func (response GetGeneration200JSONResponse) VisitGetGenerationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetGeneration404JSONResponse ErrorBody

func (response GetGeneration404JSONResponse) VisitGetGenerationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetGeneration500JSONResponse ErrorBody

func (response GetGeneration500JSONResponse) VisitGetGenerationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ScoreRequestObject struct {
	Body *ScoreJSONRequestBody
}

type ScoreResponseObject interface {
	VisitScoreResponse(w http.ResponseWriter) error
}

type Score200JSONResponse ScoreResponse

func (response Score200JSONResponse) VisitScoreResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Score400JSONResponse ErrorBody

func (response Score400JSONResponse) VisitScoreResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Score500JSONResponse ErrorBody

func (response Score500JSONResponse) VisitScoreResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type Score502JSONResponse ErrorBody

func (response Score502JSONResponse) VisitScoreResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List saved trajectories (recency-ordered)
	// (GET /builds)
	ListBuilds(ctx context.Context, request ListBuildsRequestObject) (ListBuildsResponseObject, error)
	// Fetch one saved trajectory with catalog names resolved
	// (GET /builds/{id})
	GetBuild(ctx context.Context, request GetBuildRequestObject) (GetBuildResponseObject, error)
	// Accept a saved trajectory, making it visible to RAG retrieval
	// (POST /builds/{id}/accept)
	AcceptBuild(ctx context.Context, request AcceptBuildRequestObject) (AcceptBuildResponseObject, error)
	// Enqueue an asynchronous build-generation job
	// (POST /generate)
	Generate(ctx context.Context, request GenerateRequestObject) (GenerateResponseObject, error)
	// Poll status of an enqueued generation
	// (GET /generations/{id})
	GetGeneration(ctx context.Context, request GetGenerationRequestObject) (GetGenerationResponseObject, error)
	// Score a fully-specified build
	// (POST /score)
	Score(ctx context.Context, request ScoreRequestObject) (ScoreResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListBuilds operation middleware
func (sh *strictHandler) ListBuilds(w http.ResponseWriter, r *http.Request, params ListBuildsParams) {
	var request ListBuildsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListBuilds(ctx, request.(ListBuildsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListBuilds")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListBuildsResponseObject); ok {
		if err := validResponse.VisitListBuildsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetBuild operation middleware
func (sh *strictHandler) GetBuild(w http.ResponseWriter, r *http.Request, id string) {
	var request GetBuildRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBuild(ctx, request.(GetBuildRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBuild")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBuildResponseObject); ok {
		if err := validResponse.VisitGetBuildResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AcceptBuild operation middleware
func (sh *strictHandler) AcceptBuild(w http.ResponseWriter, r *http.Request, id string) {
	var request AcceptBuildRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AcceptBuild(ctx, request.(AcceptBuildRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AcceptBuild")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AcceptBuildResponseObject); ok {
		if err := validResponse.VisitAcceptBuildResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Generate operation middleware
func (sh *strictHandler) Generate(w http.ResponseWriter, r *http.Request) {
	var request GenerateRequestObject

	var body GenerateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Generate(ctx, request.(GenerateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Generate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GenerateResponseObject); ok {
		if err := validResponse.VisitGenerateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGeneration operation middleware
func (sh *strictHandler) GetGeneration(w http.ResponseWriter, r *http.Request, id string) {
	var request GetGenerationRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGeneration(ctx, request.(GetGenerationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGeneration")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGenerationResponseObject); ok {
		if err := validResponse.VisitGetGenerationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Score operation middleware
func (sh *strictHandler) Score(w http.ResponseWriter, r *http.Request) {
	var request ScoreRequestObject

	var body ScoreJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Score(ctx, request.(ScoreRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Score")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ScoreResponseObject); ok {
		if err := validResponse.VisitScoreResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Fttbxu3lv4rB7MLrI3Kspo0wF0b/ZCmubnBdZrAdnGxuCoManikYc0hpyRHtlp4P+4P2J+4v2RxSM6L",
	"NBxLblNvgM2XSBq+HB4+5+U5Z/xbluuy0gqVs9nZb5nNCyyZ//g6z7Fy39VC8ku0lVYW6efK6AqNE+gH",
	"MT8I+Q1z9HWpTUmfMs4cnjhRYjbJ3KbC7Cyzzgi1yh4mmeA0dufnh0lm8JdaGOTZ2T9pzGRr9Z/ahfTi",
	"Z8wdLfQds/hJ1nYo14IFaeMUoRyu0NCcKo7ffbKzv18gjk5uTXoZ7ptLZv0HjjY3onJCKzpkIcqTXCtn",
	"WO7ADwLFSoSjeab0WuQ4zyYwzxzD2zutbm4Fpx+m0+lxSoEkZ1Wi8jr/V4PL7Cz7l9PuJk/jNZ6+bQZ+",
	"YBVNlLhGuW/ShR/0MMlKzXF4Fq3kBuZZZfDEoMI7JucZCAt5bQwqJzdg66rSxiFdIaq6JH32hmek6fDp",
	"p8ThLJo1mgRCJpl1LMD0MfGv/KCHSeZEWKYRYVHzFTq/O5PCOpF7+fiKlZiQZAcQQXWNDKOQuKrLkpnN",
	"XkvZ1uldgQpcgbCgNeCOWagtmpNm0jmwhUXl4FuoUHGhVnCktIPL1+9O1sKKhUQCymHm12J0+MQge6ox",
	"bx0kseaKObyxnVYeu7p3zGGjwDE/QTbJNtZtJKYxMgaflIPpHbjRS7tCf6OdY6Ru/40uF8y9McIN756z",
	"kq28uKqWki1IdGdqbJdRdbkI7skwd8jAh1EJvm/32sHf+jABSnZ/2DihDhpnMdeKv17/sVO9VVgmjAol",
	"Nm5wAISiOlDh+QiQxK/pB+GHffjy605aCeN6cfY4gN6rXJe03u++QLbGfwhXfK/56v/ixsfv8BJtLV0y",
	"WDsn8VqUeIX5QaLk0cwecyY9gyQ31ZrF/jnRhGjWwUrEBqD7lw9YfphkS4mHLV6E0+4dJ3rg2S9HC7Vd",
	"6EZdRTX3lm2OmYLv92jEGvlVE6J3wGurvjPvodXd7pO2zfLCxafTOk7zH1/nb8zwK710fdUPF4q6Hj4o",
	"DxD1g1Af2H00qr9VYwvdX409euIxKBn5pIVy9hJLJlS8+z25beFv1asgaDRcQzxi0GWUZRJurjlPI3x6",
	"5xQs3ioj8gL5SL785WRFTDo0ijmxDpIJh+XeXLM53bVhdGAd8pa4NjOG+e85k/nNGo0dy5Fy5pjUq8SY",
	"HjaeN21bCsXkjcN790xZXUM2npjuVUYcIkP6ov6kXNEfpRPtgOSxEc/ztasqRMEdZskMPxyYP7AS+SUu",
	"U3CkBZ4y3+BSKK/9kt2LksjU1zOfDoQvs8k+h+N3fOzcV4pVttDuEUL9OAlmnAvCMpOftqYfgolO6bt2",
	"kd3iBjksNnAltfs7boC4JBzdIau0mkCBjF/rapeod+ejiz/80shQQpKUurancXc/WqjVjWOGWO9Asd3v",
	"h+EgldcpHY83NEtt3Y3BhTCu6A1YaC2RKW97uTZ787ErGtRWn2jWrZByW6Pbx9ryLj3v2Wpv+EgR/z/M",
	"B/ihzWIpQO9e2lMqFjsbNi5mf+Eh4dyeYEc22t7To15rtYODjxyl2yp5jKc4v+E1DtzcCBI+gzvj4/I3",
	"xbbf65P+PF/01hhtvtM8RaPp0X4TCMNSRyfP9XGNxgiOKaNcKW3whhBcJ69xl1z3cJTcK3rJRDrpaiaH",
	"mSRTGziKpGOSSWHdcXZGdGrSbO2/jTsDXzS0I7mSxTUa4Tb9YmMVEH/HjKIUlAkZ/7spmOHJwqcrDNpC",
	"hzT598m/c2HRXbXyjV3daNHSy520ou4o6Sr7trfpPfEa2c9RDtZf7ySo0DCHb9UvNdY43rQQCQ0LjsqJ",
	"pUADS20868CwDodVWFhodU4EhAOzsNCu8KMqLSnOwi1ugCkeZq5RERDh1DMXe/qb4A80IpvsjzKPHe0S",
	"f6nRuj/cdziHdtP93GB7yaVBPCGOATZHxYzQQBvgvYOji4sP4ChNtqQioQIV8S4QtJKb40AgL1CtKC14",
	"MZvNJiPcQve9yb6kqXM9PSLx9M7DFtNop69LyuXXRHoXTDKVI7/htV+s/R4QQnb5tJZGMk4+AgCh1VXr",
	"RHeKaIS0mxS0K4OeJfvGjefUwRF/S9qUGIi0vGMbC/gLodZpEElgtBOeRDV/Dz1tI9KBRyHPQOfwFyHy",
	"UCdYspwss0RrQz3rsE6kT7XMUyXugluDnOA9CHO1UqF81iowOjPk+xtP/iri6lvKTOGkLQ4N8DHuq20c",
	"v69qRAvE0amtL5oM+9BO7M96cXgjlgYndxU29KjtuL8PTvjg9Harj7cvtY1rp0SLxcCBOLHenqj+iUMi",
	"I40KRfvUpi1hG9jOJVot18hBcDC4RIMqxzOKVWYDqi693QgOQgGDJlP/NztXLdGegM/DJ6ANNPwSAo8E",
	"W4jKwp1wBQhnIVa05sp3uYWSQuE0tLyFBSwrF+2XwmUcDAWzoDQYzLXhFIbnSnC/Wzv09af3zbBmVq7V",
	"Uqxqg3w6V77scggffCrpS+n6KgbAx8j1TpZx+RFKvQDBz2EGJTIVjuLr8WBFmSXJR2Jnz4t9MpBO6RdN",
	"vXUv0gMZ707yOB+P45JmMKKkPoVPMLvt2ui2vlCthMIWjeTtywqOFiy/RcUDnr4CzlyHWPqGxyPRa8EO",
	"bBs1vSqfDfnGxr55W/2PQUclrrFTC07q61ZI+VpKnX+G4kYKzuPFi0gs+zEssMtskkV6GT998CvRp++0",
	"720WAqV/Y8eU2viKp4ltz6XWboXMxNd5rNVm83X/y4tkyjTWR1qN9n9GnKpQI/0cWd+OxENn0g/W4pA4",
	"SdMnXtAwI4gQJAy7DnX/4AVd6oTXZivFjL6Fj96HwlEvnT2OjRFdOVGKX9FM52qu/qprA6h45bszZ3MF",
	"cAKfPl5dw6mvuUH3jwuDxAuYzM9hWUu5ObEV5kSDOHjnAP/zX/8NEb0+17Lwld/P5/Sd3+rvEulSu9HF",
	"xYcTTiuo84ZTAeuRKvhZL4iQuNooCy9mL+ArIMIU1nz39hraNYVWkUwR7YrJH+glMJWia/0VQqDuzl6x",
	"lVCUSgGl7bSGZXRI1xTRBNrh/LA5/dMKvcp2p22aIIjlqa9Wei9lwcTwS1d0XWBPTc1dNZzMksZuXn96",
	"f/P3t/8BzLWBrzKabGYK/xCu0LUD4SZz1S3UqPDV7CUcXaFZixzhR8XWTPi+8fF5AwFibELVaCnXv9Pm",
	"1iPnTcsPLTCDsM0eg23ax19Zm6t5VohVcXMnfmWGz7PjKfzQ5hZhWaUdNC28/vEWulacmU0I4044ImKZ",
	"0Sde9WhoENlUEyyy2fTr6YwMU1eoWCWys+zldDZ9SUkAc4V3GKdd8hcjMrkTj473PDvr5Y9+lmElOjQ2",
	"O/vngPgK6dCQwujqA5c+wulququEY2/y2RkRAN/+CblGVwX1ESOZfDy+Z6CRBIOlkNhuXjOjx3dtO1RP",
	"2DZnFeGVIiAccVyyWjp4NYGS3cOr2dhOUpTe3XUbtQXWV/0C69epHGfk5ItNhArxbG/veA7O1Ajfdhgi",
	"NjiBJZMWd1vBG+ywdhwH6lI4mvYtMCk91lKnaWalNNe2MR5+It8fchuPsRezmc9qtHJNZ6qqpMg94E5/",
	"jhXEbsFHezlDauMDxbaiLqL36jmg0GkUoRzyzWeUqCshJwR5r9ZMCg5ej9CaEsnw6rlkuBALw8wGTgFV",
	"rjkCkezaoA/Sbbs66Gzo7uHIYI4q35xow9EgP/bz+q5/1I+8w3BX+7yIJ1/kpkMtv3PeR9q0QSoUeCMu",
	"yZV1sPSJV5duhBeBxk37z8Tn9qsdidu4SkZG9NN8dvic8BQcSJMdMKEU1sZs85vZN88jxQ96oA9XMAeC",
	"f4l28ld0eRFCT/IqGwq+neEMjOY0+FKfzWuboMUfmLm1vTd9dl/0mcKPygnZevIJsChRGC8sLElUSnJg",
	"LZhP2bYytgVlSxZ++HgNtjZLlgfzoy0NOiNw7eueWlrKsDXLnVhTwEUOQtGZhVYTWKG7saIUkpmbill3",
	"E7aID0ig8MvxFN5zLCtN13gGBuNJQp8Aq3BWbQSloBKcKNEz25D5bDuW3p9hHOBbKBAUuKUcp6PevniH",
	"kvqLkwR4AzFpoz85TiYNMr7pQv3/Z6NO23JQbms4ncCU1t0SMoWD+NYcYeby9bvONIJJN7Fq3JBj680O",
	"+J1vjTX8RJQlcsEcys0UPmlKwoYEr/YWHxmesDDviufzDLSBeaygz7PpXF1irssSFUceqGHOeKhv/ufL",
	"GYR30O30M3CvueqRL3CFsP01Ov7VtALp7MKCQsrcG4qasvOmxRetsVfY+yzI2e0gPmyXLcjsHwam/eKz",
	"b7/bm03AuGt1tfo6D3c6BMlSmwiRZ80lohLBJ7xB1IBFOCo1x9O2kXjamxd80ot/fx4Re1qMFRcHOatY",
	"LtwmeKWXzyMIGY+wYIva+fjH9Z3y1R6zAcmcp6YFMu5D2m/ZJT04eb10oV86CEQdZXzY9m9vm8qSAmY3",
	"Ki+MVrq2IQiebHujLXfWoumx3L5T5zAIf9lBddA5fhwsfWt6pvD5o7pV+k59oTnwp0MKjQFQ7SuN6eD4",
	"hsn8JJZcCS5TeMOkROP/XlIS/wxvnThhMFZfj3zNaBK6bZO58hXYCbQduePzkO4JjjnzlSFe52h3KrZM",
	"8QmIJbC5aho40+vQthMWVmKNijLqrpoLbMWEsi6kMaVepAKWb+z8SdFq0N86KFzNPvf+40HqjS6rmrLP",
	"cOfPGXwCMoahh0JhxIHB8Pe3wOCb+3s4yj3OTpbi3peBn9XMflR4X2HuPJPyf2IhG0uDI2eYsiTrJBph",
	"lO3F88h2NdTXK9JXo8fcMFvAqS+EQ8WUyI93vIMHCrBB82TR1URCATbF1y50ziRwsm1dxXZZbWR2lhXO",
	"VWenp5IGFNq6s7/M/jLLHn56+N8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
