apiVersion: v1
kind: Service
metadata:
  name: {{ include "ro-builder.apiName" . }}
  labels:
    {{- include "ro-builder.labels" (dict "component" "api" "root" .) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    {{- include "ro-builder.selectorLabels" (dict "component" "api" "root" .) | nindent 4 }}
