apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ro-builder.sidecarName" . }}
  labels:
    {{- include "ro-builder.labels" (dict "component" "sidecar" "root" .) | nindent 4 }}
automountServiceAccountToken: false
